_id: "415405684872445952"
name: test1
description: null
model: gpt-3.5-turbo
createdAt: 2024-02-21T07:13:53.138Z
updatedAt: 2024-02-23T06:20:11.467Z
createdBy: z1VhQ6KSjPafNF1oTK8scHNdvz7SxWngeVq
updatedBy: z1VhQ6KSjPafNF1oTK8scHNdvz7SxWngeVq
pinnedAt: null
icon: ""
gitType: simple
temperature: 1
topP: 1
presencePenalty: null
frequencyPenalty: null
maxTokens: null
gitAutoSync: true
