_id: "415405684872445952"
name: test1
description: null
model: ""
createdAt: 2024-02-21T07:13:53.138Z
updatedAt: 2024-02-21T07:40:38.274Z
createdBy: z1VhQ6KSjPafNF1oTK8scHNdvz7SxWngeVq
updatedBy: z1VhQ6KSjPafNF1oTK8scHNdvz7SxWngeVq
pinnedAt: null
icon: ""
gitType: simple
temperature: 1
topP: 1
presencePenalty: null
frequencyPenalty: null
maxTokens: null
gitAutoSync: null
