_id: "415421910063513600"
name: remote test1
description: null
model: ""
createdAt: 2024-02-21T08:18:21.526Z
updatedAt: 2024-02-21T08:40:16.353Z
createdBy: z1VhQ6KSjPafNF1oTK8scHNdvz7SxWngeVq
updatedBy: z1VhQ6KSjPafNF1oTK8scHNdvz7SxWngeVq
pinnedAt: null
icon: https://bbqasaloioeeahlpskse66262a3p76d32jihsvrw2h4.did.abtnet.io/image-bin/uploads/028bf787919e3e25bd5aca113c5471bb.png
gitType: simple
temperature: 1
topP: 1
presencePenalty: null
frequencyPenalty: null
maxTokens: null
gitAutoSync: null
