_id: "415405684872445952"
name: test1
model: ""
createdAt: 2024-02-21T07:13:53.138Z
updatedAt: 2024-02-21T07:13:53.138Z
createdBy: z1VhQ6KSjPafNF1oTK8scHNdvz7SxWngeVq
updatedBy: z1VhQ6KSjPafNF1oTK8scHNdvz7SxWngeVq
icon: ""
gitType: simple
temperature: 1
topP: 1
