_id: "420397833363914752"
name: 项目B233
description: 描述B
model: gpt-3.5-turbo-16k
createdAt: 2024-03-06T01:50:54.089Z
updatedAt: 2024-03-06T05:42:42.099Z
createdBy: z1g2f6W3uALzkp3758gqHFq4aqN6ppNrak6
updatedBy: z1g2f6W3uALzkp3758gqHFq4aqN6ppNrak6
pinnedAt: null
icon: https://bbqaw27jkdemvnr4bkk5qdla3qt522rh52lgzxmqrc4.did.abtnet.io/image-bin/uploads/ad4c3fef05e2841da5b17fb6a4e2e34b.png
gitType: simple
temperature: 1
topP: 1
presencePenalty: null
frequencyPenalty: null
maxTokens: null
gitAutoSync: true
